"""add card number expiry cvv and card_orders.card_id link

Revision ID: 2a2321e7ddfa
Revises: f4a724d90b70
Create Date: 2026-08-19 07:24:26.577217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a2321e7ddfa'
down_revision: Union[str, None] = 'f4a724d90b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_orders', sa.Column('card_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_card_orders_card_id'), 'card_orders', ['card_id'], unique=True)
    op.create_foreign_key(None, 'card_orders', 'cards', ['card_id'], ['id'], ondelete='RESTRICT')
    op.add_column('cards', sa.Column('card_number', sa.String(length=19), nullable=False))
    op.add_column('cards', sa.Column('expiry_month', sa.SmallInteger(), nullable=False))
    op.add_column('cards', sa.Column('expiry_year', sa.SmallInteger(), nullable=False))
    op.add_column('cards', sa.Column('cvv', sa.String(length=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'cvv')
    op.drop_column('cards', 'expiry_year')
    op.drop_column('cards', 'expiry_month')
    op.drop_column('cards', 'card_number')
    op.drop_constraint(None, 'card_orders', type_='foreignkey')
    op.drop_index(op.f('ix_card_orders_card_id'), table_name='card_orders')
    op.drop_column('card_orders', 'card_id')
    # ### end Alembic commands ###
