"""add cards table

Revision ID: a0a1f0aad9e4
Revises: 72cc9992624f
Create Date: 2026-08-18 12:05:39.595763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a1f0aad9e4'
down_revision: Union[str, None] = '72cc9992624f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('status', sa.Enum('active', 'frozen', 'cancelled', name='card_status', native_enum=False, length=10), nullable=False),
    sa.Column('spending_limit_minor', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_account_id'), 'cards', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_account_id'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
